### ISSUE TITLE
Clean up/organize Repo

### ISSUE THREAD

**Issue by MaximumWoahverdrive** [HerissonMignion/FactorioOrganizer#1]
While it's workable the Repo in its current state is quite messy and doesn't contain all the files it should to allow people to easily work with it. 
It also goes against quite a few (unwritten) rules of git, namely:
Executable in the project files (considered a sin by many and for good reason. these belong in the tags/releases)
Not having a .sln (while you can work with just the .csproj it is a bit cumbersome at best)
Cluttered top level directory
missing .gitattributes and .gitignore (the latter of which can be severe)
.txt files in the repo (the info in these should almost always be in the git wiki, in code comments or  the readme)

If it's ok for you I'll open a Pull request with these issues fixed

**Comment by HerissonMignion** [comment]
I'm new to github development. I'll pass all the day to learn more about it, set up visual studio etc. I would be happy if you open a pull request with the issue fixed, but honestly i don't know what this is yet, but i'll learn on the fly!!! (I think i'll practice with my other repos because i don't want to mess up with the 22 stars).   I know (i think) that i/we have to make a new folder named "FactorioOrganizer" and move all the current files in it and put the sln at the root of the repo so it looks more like a normal project.     
[FactorioOrganizer.sln.txt](https://github.com/HerissonMignion/FactorioOrganizer/files/3509756/FactorioOrganizer.sln.txt)

**Comment by ultranoobian** [comment]
I've made a PR #2 just to start with a 'bog-standard' gitignore and gitattributes file for VS.

**Comment by HerissonMignion** [comment]
ultranoobian, I downloaded and installed github eextension for vs. Now in local, i'm making it look like a normal solution, with a sln and the .gitignore at the root. Is this how it should be? I looked on github other c# project and i saw that it's often like that.

**Comment by HerissonMignion** [comment]
I hope you realize how much help i need. I won't be able to fix that myself because i have a lot of trouble and i don't truly know what should be done to fix that. I need your help. Right now my bigest problem i think is the change tab in the VS extension. It show me 74134 changes (file to add) because it consider my whole user folder. Where i am, it's 12:00 am and i can stay until 11:00pm. Even after i fix my problem with the extension/understand how it work, i still don't know what should be done to fix that.

**Comment by MaximumWoahverdrive** [comment]
@HerissonMignion  your previous assumption on how the repo should look. 
> make a new folder named "FactorioOrganizer" and move all the current files in it and put the sln at the root of the repo  

I've opened a pull request #3 which does exactly that.

**Comment by MaximumWoahverdrive** [comment]
Another thing to mention is that while the extension previously mentioned is useful, it is not at all needed to work with a github repository in visual studio.
I believe the wrong file structure was caused by manually pushing the files using git commandline, generally when using visual studio it is much easier to use its built in tools to push and pull a repository.

**Comment by HerissonMignion** [comment]
The wrong file structure was causing by me uploading files manually from the web interface. I'm looking to aprove your pull request. Thanks! I've never stop searching since this morning.

**Comment by MaximumWoahverdrive** [comment]
The webinterface was also the thing limiting your file upload to 100 files. That limit doesnt apply when pushing normally with visual studio or in git bash/commandline
